{% import '.cookiecutter_includes/license_header.j2' as license_macros with context %}
{{- license_macros.license_header(
	cookiecutter.license,
	cookiecutter.author,
	cookiecutter.project_slug,
	file_name='black-format.yml',
	comment_style='hash') -}}
---
name: Cookiecutter Template Format Check

on: [push, pull_request]

jobs:
  black-format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Formatting Tools
        run: |
          make install

      - name: Black Format Check
        run: |
          make black-formatter-check
