{% import '.cookiecutter_includes/license_header.j2' as license_macros with context %}
{{- license_macros.license_header(
	cookiecutter.license,
	cookiecutter.author,
	cookiecutter.project_slug,
	file_name='lint-check.yml',
	comment_style='hash') -}}
---
name: Cookiecutter Template Lint Check

on: [push, pull_request]

jobs:
  jinja2-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Linting Tools
        run: |
          make install

      - name: Render Cookiecutter Template
        run: |
          make render-cookiecutter

      - name: Lint Jinja templates
        run: |
          make jinja2-lint-check
      - name: Run Ruff Lint Check
        run: |
          make ruff-lint-check
      - name: Run Toml Lint Check
        run: |
          make toml-lint-check
      - name: Run YAML Lint Check
        run: |
          make yaml-lint-check
