{%- macro makefile(
    template_type,
) -%}
{% if template_type == "ansible" -%}

{%- elif template_type == "cookiecutter" -%}

{%- elif template_type == "github-docs" -%}

{%- elif template_type == "python" -%}

{%- elif template_type == "ros2" -%}

{%- elif template_type == "sphinx-docs" -%}

{%- elif template_type == "typescript" -%}

{% endif -%}
{%- endmacro -%}
